{
    'name': 'MA Service',
    'version': '18.0.1.0.0',
    'category': 'MA ERP',
    'summary': 'Service division — PRO contracts, job tracking, recurring billing',
    'author': 'MA ERP',
    'license': 'LGPL-3',
    'depends': [
        'ma_base',
        'project',
        'account',
        'portal',
        'mail',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/service_type_data.xml',
        'data/mail_template_data.xml',
        'data/cron_data.xml',
        'views/service_type_views.xml',
        'views/project_task_views.xml',
        'views/contract_views.xml',
        'views/menu_views.xml',
        'reports/job_report.xml',
    ],
    'installable': True,
    'auto_install': False,
}
