version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ma_erp_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_password
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ma_erp_net

  odoo:
    image: odoo:18
    container_name: ma_erp_odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./docker/odoo.conf:/etc/odoo/odoo.conf
      - odoo_data:/var/lib/odoo
    restart: unless-stopped
    networks:
      - ma_erp_net

volumes:
  db_data:
  odoo_data:

networks:
  ma_erp_net:
    driver: bridge
