{
    'name': 'MA Contracting',
    'version': '18.0.1.0.0',
    'category': 'MA ERP',
    'summary': 'Contracting division — projects, BOQ, payment milestones, retention tracking',
    'author': 'MA ERP',
    'license': 'LGPL-3',
    'depends': [
        'ma_base',
        'project',
        'sale_management',
        'account',
        'uom',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/project_type_data.xml',
        'data/sequence_data.xml',
        'views/project_type_views.xml',
        'views/project_views.xml',
        'views/payment_views.xml',
        'views/sale_order_views.xml',
        'views/partner_views.xml',
        'views/menu_views.xml',
        'reports/boq_report.xml',
        'reports/payment_schedule_report.xml',
        'reports/project_profitability_report.xml',
    ],
    'installable': True,
    'auto_install': False,
}
